var CountryList = {
    AFGHANISTAN: { value: 1, name: "Afghanistan", Code: "AF" },
    ÅLANDISLANDS: { value: 1, name: "Åland Islands", Code: "AX" },
    ALBANIA: { value: 1, name: "Albania", Code: "AL" },
    ALGERIA: { value: 1, name: "Algeria", Code: "DZ" },
    AMERICANSAMOA: { value: 1, name: "American Samoa", Code: "AS" },
    ANDORRA: { value: 1, name: "Andorra", Code: "AD" },
    ANGOLA: { value: 1, name: "Angola", Code: "AO" },
    ANGUILLA: { value: 1, name: "Anguilla", Code: "AI" },
    ANTARCTICA: { value: 1, name: "Antarctica", Code: "AQ" },
    ANTIGUAANDBARBUDA: { value: 1, name: "Antigua and Barbuda", Code: "AG" },
    ARGENTINA: { value: 1, name: "Argentina", Code: "AR" },
    ARMENIA: { value: 1, name: "Armenia", Code: "AM" },
    ARUBA: { value: 1, name: "Aruba", Code: "AW" },
    AUSTRALIA: { value: 1, name: "Australia", Code: "AU" },
    AUSTRIA: { value: 1, name: "Austria", Code: "AT" },
    AZERBAIJAN: { value: 1, name: "Azerbaijan", Code: "AZ" },
    BAHAMAS: { value: 1, name: "Bahamas", Code: "BS" },
    BAHRAIN: { value: 1, name: "Bahrain", Code: "BH" },
    BANGLADESH: { value: 1, name: "Bangladesh", Code: "BD" },
    BARBADOS: { value: 1, name: "Barbados", Code: "BB" },
    BELARUS: { value: 1, name: "Belarus", Code: "BY" },
    BELGIUM: { value: 1, name: "Belgium", Code: "BE" },
    BELIZE: { value: 1, name: "Belize", Code: "BZ" },
    BENIN: { value: 1, name: "Benin", Code: "BJ" },
    BERMUDA: { value: 1, name: "Bermuda", Code: "BM" },
    BHUTAN: { value: 1, name: "Bhutan", Code: "BT" },
    BOLIVIAPLURINATIONALSTATEOF: { value: 1, name: "Bolivia, Plurinational State of", Code: "BO" },
    BONAIRESINTEUSTATIUSANDSABA: { value: 1, name: "Bonaire, Sint Eustatius and Saba", Code: "BQ" },
    BOSNIAANDHERZEGOVINA: { value: 1, name: "Bosnia and Herzegovina", Code: "BA" },
    BOTSWANA: { value: 1, name: "Botswana", Code: "BW" },
    BOUVETISLAND: { value: 1, name: "Bouvet Island", Code: "BV" },
    BRAZIL: { value: 1, name: "Brazil", Code: "BR" },
    BRITISHINDIANOCEANTERRITORY: { value: 1, name: "British Indian Ocean Territory", Code: "IO" },
    BRUNEIDARUSSALAM: { value: 1, name: "Brunei Darussalam", Code: "BN" },
    BULGARIA: { value: 1, name: "Bulgaria", Code: "BG" },
    BURKINAFASO: { value: 1, name: "Burkina Faso", Code: "BF" },
    BURUNDI: { value: 1, name: "Burundi", Code: "BI" },
    CAMBODIA: { value: 1, name: "Cambodia", Code: "KH" },
    CAMEROON: { value: 1, name: "Cameroon", Code: "CM" },
    CANADA: { value: 1, name: "Canada", Code: "CA" },
    CAPEVERDE: { value: 1, name: "Cape Verde", Code: "CV" },
    CAYMANISLANDS: { value: 1, name: "Cayman Islands", Code: "KY" },
    CENTRALAFRICANREPUBLIC: { value: 1, name: "Central African Republic", Code: "CF" },
    CHAD: { value: 1, name: "Chad", Code: "TD" },
    CHILE: { value: 1, name: "Chile", Code: "CL" },
    CHINA: { value: 1, name: "China", Code: "CN" },
    CHRISTMASISLAND: { value: 1, name: "Christmas Island", Code: "CX" },
    COCOSKEELINGISLANDS: { value: 1, name: "Cocos (Keeling) Islands", Code: "CC" },
    COLOMBIA: { value: 1, name: "Colombia", Code: "CO" },
    COMOROS: { value: 1, name: "Comoros", Code: "KM" },
    CONGO: { value: 1, name: "Congo", Code: "CG" },
    CONGOTHEDEMOCRATICREPUBLICOFTHE: { value: 1, name: "Congo, the Democratic Republic of the", Code: "CD" },
    COOKISLANDS: { value: 1, name: "Cook Islands", Code: "CK" },
    COSTARICA: { value: 1, name: "Costa Rica", Code: "CR" },
    CÔTEDIVOIRE: { value: 1, name: "Côte d'Ivoire", Code: "CI" },
    CROATIA: { value: 1, name: "Croatia", Code: "HR" },
    CUBA: { value: 1, name: "Cuba", Code: "CU" },
    CURAÇAO: { value: 1, name: "Curaçao", Code: "CW" },
    CYPRUS: { value: 1, name: "Cyprus", Code: "CY" },
    CZECHREPUBLIC: { value: 1, name: "Czech Republic", Code: "CZ" },
    DENMARK: { value: 1, name: "Denmark", Code: "DK" },
    DJIBOUTI: { value: 1, name: "Djibouti", Code: "DJ" },
    DOMINICA: { value: 1, name: "Dominica", Code: "DM" },
    DOMINICANREPUBLIC: { value: 1, name: "Dominican Republic", Code: "DO" },
    ECUADOR: { value: 1, name: "Ecuador", Code: "EC" },
    EGYPT: { value: 1, name: "Egypt", Code: "EG" },
    ELSALVADOR: { value: 1, name: "El Salvador", Code: "SV" },
    EQUATORIALGUINEA: { value: 1, name: "Equatorial Guinea", Code: "GQ" },
    ERITREA: { value: 1, name: "Eritrea", Code: "ER" },
    ESTONIA: { value: 1, name: "Estonia", Code: "EE" },
    ETHIOPIA: { value: 1, name: "Ethiopia", Code: "ET" },
    FALKLANDISLANDSMALVINAS: { value: 1, name: "Falkland Islands (Malvinas)", Code: "FK" },
    FAROEISLANDS: { value: 1, name: "Faroe Islands", Code: "FO" },
    FIJI: { value: 1, name: "Fiji", Code: "FJ" },
    FINLAND: { value: 1, name: "Finland", Code: "FI" },
    FRANCE: { value: 1, name: "France", Code: "FR" },
    FRENCHGUIANA: { value: 1, name: "French Guiana", Code: "GF" },
    FRENCHPOLYNESIA: { value: 1, name: "French Polynesia", Code: "PF" },
    FRENCHSOUTHERNTERRITORIES: { value: 1, name: "French Southern Territories", Code: "TF" },
    GABON: { value: 1, name: "Gabon", Code: "GA" },
    GAMBIA: { value: 1, name: "Gambia", Code: "GM" },
    GEORGIA: { value: 1, name: "Georgia", Code: "GE" },
    GERMANY: { value: 1, name: "Germany", Code: "DE" },
    GHANA: { value: 1, name: "Ghana", Code: "GH" },
    GIBRALTAR: { value: 1, name: "Gibraltar", Code: "GI" },
    GREECE: { value: 1, name: "Greece", Code: "GR" },
    GREENLAND: { value: 1, name: "Greenland", Code: "GL" },
    GRENADA: { value: 1, name: "Grenada", Code: "GD" },
    GUADELOUPE: { value: 1, name: "Guadeloupe", Code: "GP" },
    GUAM: { value: 1, name: "Guam", Code: "GU" },
    GUATEMALA: { value: 1, name: "Guatemala", Code: "GT" },
    GUERNSEY: { value: 1, name: "Guernsey", Code: "GG" },
    GUINEA: { value: 1, name: "Guinea", Code: "GN" },
    GUINEABISSAU: { value: 1, name: "Guinea-Bissau", Code: "GW" },
    GUYANA: { value: 1, name: "Guyana", Code: "GY" },
    HAITI: { value: 1, name: "Haiti", Code: "HT" },
    HEARDISLANDANDMCDONALDISLANDS: { value: 1, name: "Heard Island and McDonald Islands", Code: "HM" },
    HOLYSEEVATICANCITYSTATE: { value: 1, name: "Holy See (Vatican City State)", Code: "VA" },
    HONDURAS: { value: 1, name: "Honduras", Code: "HN" },
    HONGKONG: { value: 1, name: "Hong Kong", Code: "HK" },
    HUNGARY: { value: 1, name: "Hungary", Code: "HU" },
    ICELAND: { value: 1, name: "Iceland", Code: "IS" },
    INDIA: { value: 1, name: "India", Code: "IN" },
    INDONESIA: { value: 1, name: "Indonesia", Code: "ID" },
    IRANISLAMICREPUBLICOF: { value: 1, name: "Iran, Islamic Republic of", Code: "IR" },
    IRAQ: { value: 1, name: "Iraq", Code: "IQ" },
    IRELAND: { value: 1, name: "Ireland", Code: "IE" },
    ISLEOFMAN: { value: 1, name: "Isle of Man", Code: "IM" },
    ISRAEL: { value: 1, name: "Israel", Code: "IL" },
    ITALY: { value: 1, name: "Italy", Code: "IT" },
    JAMAICA: { value: 1, name: "Jamaica", Code: "JM" },
    JAPAN: { value: 1, name: "Japan", Code: "JP" },
    JERSEY: { value: 1, name: "Jersey", Code: "JE" },
    JORDAN: { value: 1, name: "Jordan", Code: "JO" },
    KAZAKHSTAN: { value: 1, name: "Kazakhstan", Code: "KZ" },
    KENYA: { value: 1, name: "Kenya", Code: "KE" },
    KIRIBATI: { value: 1, name: "Kiribati", Code: "KI" },
    KOREADEMOCRATICPEOPLESREPUBLICOF: { value: 1, name: "Korea, Democratic People's Republic of", Code: "KP" },
    KOREAREPUBLICOF: { value: 1, name: "Korea, Republic of", Code: "KR" },
    KUWAIT: { value: 1, name: "Kuwait", Code: "KW" },
    KYRGYZSTAN: { value: 1, name: "Kyrgyzstan", Code: "KG" },
    LAOPEOPLESDEMOCRATICREPUBLIC: { value: 1, name: "Lao People's Democratic Republic", Code: "LA" },
    LATVIA: { value: 1, name: "Latvia", Code: "LV" },
    LEBANON: { value: 1, name: "Lebanon", Code: "LB" },
    LESOTHO: { value: 1, name: "Lesotho", Code: "LS" },
    LIBERIA: { value: 1, name: "Liberia", Code: "LR" },
    LIBYA: { value: 1, name: "Libya", Code: "LY" },
    LIECHTENSTEIN: { value: 1, name: "Liechtenstein", Code: "LI" },
    LITHUANIA: { value: 1, name: "Lithuania", Code: "LT" },
    LUXEMBOURG: { value: 1, name: "Luxembourg", Code: "LU" },
    MACAO: { value: 1, name: "Macao", Code: "MO" },
    MACEDONIATHEFORMERYUGOSLAVREPUBLICOF: { value: 1, name: "Macedonia, the former Yugoslav Republic of", Code: "MK" },
    MADAGASCAR: { value: 1, name: "Madagascar", Code: "MG" },
    MALAWI: { value: 1, name: "Malawi", Code: "MW" },
    MALAYSIA: { value: 1, name: "Malaysia", Code: "MY" },
    MALDIVES: { value: 1, name: "Maldives", Code: "MV" },
    MALI: { value: 1, name: "Mali", Code: "ML" },
    MALTA: { value: 1, name: "Malta", Code: "MT" },
    MARSHALLISLANDS: { value: 1, name: "Marshall Islands", Code: "MH" },
    MARTINIQUE: { value: 1, name: "Martinique", Code: "MQ" },
    MAURITANIA: { value: 1, name: "Mauritania", Code: "MR" },
    MAURITIUS: { value: 1, name: "Mauritius", Code: "MU" },
    MAYOTTE: { value: 1, name: "Mayotte", Code: "YT" },
    MEXICO: { value: 1, name: "Mexico", Code: "MX" },
    MICRONESIAFEDERATEDSTATESOF: { value: 1, name: "Micronesia, Federated States of", Code: "FM" },
    MOLDOVAREPUBLICOF: { value: 1, name: "Moldova, Republic of", Code: "MD" },
    MONACO: { value: 1, name: "Monaco", Code: "MC" },
    MONGOLIA: { value: 1, name: "Mongolia", Code: "MN" },
    MONTENEGRO: { value: 1, name: "Montenegro", Code: "ME" },
    MONTSERRAT: { value: 1, name: "Montserrat", Code: "MS" },
    MOROCCO: { value: 1, name: "Morocco", Code: "MA" },
    MOZAMBIQUE: { value: 1, name: "Mozambique", Code: "MZ" },
    MYANMAR: { value: 1, name: "Myanmar", Code: "MM" },
    NAMIBIA: { value: 1, name: "Namibia", Code: "NA" },
    NAURU: { value: 1, name: "Nauru", Code: "NR" },
    NEPAL: { value: 1, name: "Nepal", Code: "NP" },
    NETHERLANDS: { value: 1, name: "Netherlands", Code: "NL" },
    NEWCALEDONIA: { value: 1, name: "New Caledonia", Code: "NC" },
    NEWZEALAND: { value: 1, name: "New Zealand", Code: "NZ" },
    NICARAGUA: { value: 1, name: "Nicaragua", Code: "NI" },
    NIGER: { value: 1, name: "Niger", Code: "NE" },
    NIGERIA: { value: 1, name: "Nigeria", Code: "NG" },
    NIUE: { value: 1, name: "Niue", Code: "NU" },
    NORFOLKISLAND: { value: 1, name: "Norfolk Island", Code: "NF" },
    NORTHERNMARIANAISLANDS: { value: 1, name: "Northern Mariana Islands", Code: "MP" },
    NORWAY: { value: 1, name: "Norway", Code: "NO" },
    OMAN: { value: 1, name: "Oman", Code: "OM" },
    PAKISTAN: { value: 1, name: "Pakistan", Code: "PK" },
    PALAU: { value: 1, name: "Palau", Code: "PW" },
    PALESTINIANTERRITORYOCCUPIED: { value: 1, name: "Palestinian Territory, Occupied", Code: "PS" },
    PANAMA: { value: 1, name: "Panama", Code: "PA" },
    PAPUANEWGUINEA: { value: 1, name: "Papua New Guinea", Code: "PG" },
    PARAGUAY: { value: 1, name: "Paraguay", Code: "PY" },
    PERU: { value: 1, name: "Peru", Code: "PE" },
    PHILIPPINES: { value: 1, name: "Philippines", Code: "PH" },
    PITCAIRN: { value: 1, name: "Pitcairn", Code: "PN" },
    POLAND: { value: 1, name: "Poland", Code: "PL" },
    PORTUGAL: { value: 1, name: "Portugal", Code: "PT" },
    PUERTORICO: { value: 1, name: "Puerto Rico", Code: "PR" },
    QATAR: { value: 1, name: "Qatar", Code: "QA" },
    RÉUNION: { value: 1, name: "Réunion", Code: "RE" },
    ROMANIA: { value: 1, name: "Romania", Code: "RO" },
    RUSSIANFEDERATION: { value: 1, name: "Russian Federation", Code: "RU" },
    RWANDA: { value: 1, name: "Rwanda", Code: "RW" },
    SAINTBARTHÉLEMY: { value: 1, name: "Saint Barthélemy", Code: "BL" },
    SAINTHELENAASCENSIONANDTRISTANDACUNHA: { value: 1, name: "Saint Helena, Ascension and Tristan da Cunha", Code: "SH" },
    SAINTKITTSANDNEVIS: { value: 1, name: "Saint Kitts and Nevis", Code: "KN" },
    SAINTLUCIA: { value: 1, name: "Saint Lucia", Code: "LC" },
    SAINTMARTINFRENCHPART: { value: 1, name: "Saint Martin (French part)", Code: "MF" },
    SAINTPIERREANDMIQUELON: { value: 1, name: "Saint Pierre and Miquelon", Code: "PM" },
    SAINTVINCENTANDTHEGRENADINES: { value: 1, name: "Saint Vincent and the Grenadines", Code: "VC" },
    SAMOA: { value: 1, name: "Samoa", Code: "WS" },
    SANMARINO: { value: 1, name: "San Marino", Code: "SM" },
    SAOTOMEANDPRINCIPE: { value: 1, name: "Sao Tome and Principe", Code: "ST" },
    SAUDIARABIA: { value: 1, name: "Saudi Arabia", Code: "SA" },
    SENEGAL: { value: 1, name: "Senegal", Code: "SN" },
    SERBIA: { value: 1, name: "Serbia", Code: "RS" },
    SEYCHELLES: { value: 1, name: "Seychelles", Code: "SC" },
    SIERRALEONE: { value: 1, name: "Sierra Leone", Code: "SL" },
    SINGAPORE: { value: 1, name: "Singapore", Code: "SG" },
    SINTMAARTENDUTCHPART: { value: 1, name: "Sint Maarten (Dutch part)", Code: "SX" },
    SLOVAKIA: { value: 1, name: "Slovakia", Code: "SK" },
    SLOVENIA: { value: 1, name: "Slovenia", Code: "SI" },
    SOLOMONISLANDS: { value: 1, name: "Solomon Islands", Code: "SB" },
    SOMALIA: { value: 1, name: "Somalia", Code: "SO" },
    SOUTHAFRICA: { value: 1, name: "South Africa", Code: "ZA" },
    SOUTHGEORGIAANDTHESOUTHSANDWICHISLANDS: { value: 1, name: "South Georgia and the South Sandwich Islands", Code: "GS" },
    SOUTHSUDAN: { value: 1, name: "South Sudan", Code: "SS" },
    SPAIN: { value: 1, name: "Spain", Code: "ES" },
    SRILANKA: { value: 1, name: "Sri Lanka", Code: "LK" },
    SUDAN: { value: 1, name: "Sudan", Code: "SD" },
    SURINAME: { value: 1, name: "Suriname", Code: "SR" },
    SVALBARDANDJANMAYEN: { value: 1, name: "Svalbard and Jan Mayen", Code: "SJ" },
    SWAZILAND: { value: 1, name: "Swaziland", Code: "SZ" },
    SWEDEN: { value: 1, name: "Sweden", Code: "SE" },
    SWITZERLAND: { value: 1, name: "Switzerland", Code: "CH" },
    SYRIANARABREPUBLIC: { value: 1, name: "Syrian Arab Republic", Code: "SY" },
    TAIWANPROVINCEOFCHINA: { value: 1, name: "Taiwan, Province of China", Code: "TW" },
    TAJIKISTAN: { value: 1, name: "Tajikistan", Code: "TJ" },
    TANZANIAUNITEDREPUBLICOF: { value: 1, name: "Tanzania, United Republic of", Code: "TZ" },
    THAILAND: { value: 1, name: "Thailand", Code: "TH" },
    TIMORLESTE: { value: 1, name: "Timor-Leste", Code: "TL" },
    TOGO: { value: 1, name: "Togo", Code: "TG" },
    TOKELAU: { value: 1, name: "Tokelau", Code: "TK" },
    TONGA: { value: 1, name: "Tonga", Code: "TO" },
    TRINIDADANDTOBAGO: { value: 1, name: "Trinidad and Tobago", Code: "TT" },
    TUNISIA: { value: 1, name: "Tunisia", Code: "TN" },
    TURKEY: { value: 1, name: "Turkey", Code: "TR" },
    TURKMENISTAN: { value: 1, name: "Turkmenistan", Code: "TM" },
    TURKSANDCAICOSISLANDS: { value: 1, name: "Turks and Caicos Islands", Code: "TC" },
    TUVALU: { value: 1, name: "Tuvalu", Code: "TV" },
    UGANDA: { value: 1, name: "Uganda", Code: "UG" },
    UKRAINE: { value: 1, name: "Ukraine", Code: "UA" },
    UNITEDARABEMIRATES: { value: 1, name: "United Arab Emirates", Code: "AE" },
    UNITEDKINGDOM: { value: 1, name: "United Kingdom", Code: "GB" },
    UNITEDSTATES: { value: 1, name: "United States", Code: "US" },
    UNITEDSTATESMINOROUTLYINGISLANDS: { value: 1, name: "United States Minor Outlying Islands", Code: "UM" },
    URUGUAY: { value: 1, name: "Uruguay", Code: "UY" },
    UZBEKISTAN: { value: 1, name: "Uzbekistan", Code: "UZ" },
    VANUATU: { value: 1, name: "Vanuatu", Code: "VU" },
    VENEZUELABOLIVARIANREPUBLICOF: { value: 1, name: "Venezuela, Bolivarian Republic of", Code: "VE" },
    VIETNAM: { value: 1, name: "Viet Nam", Code: "VN" },
    VIRGINISLANDSBRITISH: { value: 1, name: "Virgin Islands, British", Code: "VG" },
    VIRGINISLANDSUS: { value: 1, name: "Virgin Islands, U.S.", Code: "VI" },
    WALLISANDFUTUNA: { value: 1, name: "Wallis and Futuna", Code: "WF" },
    WESTERNSAHARA: { value: 1, name: "Western Sahara", Code: "EH" },
    YEMEN: { value: 1, name: "Yemen", Code: "YE" },
    ZAMBIA: { value: 1, name: "Zambia", Code: "ZM" },
    ZIMBABWE: { value: 1, name: "Zimbabwe", Code: "ZW" }
};

var UnitedStatesProvinces = {
    ALABAMA: { code: "AL", Country: "United States", name: "Alabama" },
    ALASKA: { code: "AK", Country: "United States", name: "Alaska" },
    ARIZONA: { code: "AZ", Country: "United States", name: "Arizona" },
    ARKANSAS: { code: "AR", Country: "United States", name: "Arkansas" },
    CALIFORNIA: { code: "CA", Country: "United States", name: "California" },
    COLORADO: { code: "CO", Country: "United States", name: "Colorado" },
    CONNECTICUT: { code: "CT", Country: "United States", name: "Connecticut" },
    DELAWARE: { code: "DE", Country: "United States", name: "Delaware" },
    DISTRICTOFCOLUMBIA: { code: "DC", Country: "United States", name: "District Of Columbia" },
    FLORIDA: { code: "FL", Country: "United States", name: "Florida" },
    GEORGIA: { code: "GA", Country: "United States", name: "Georgia" },
    HAWAII: { code: "HI", Country: "United States", name: "Hawaii" },
    IDAHO: { code: "ID", Country: "United States", name: "Idaho" },
    ILLINOIS: { code: "IL", Country: "United States", name: "Illinois" },
    INDIANA: { code: "IN", Country: "United States", name: "Indiana" },
    IOWA: { code: "IA", Country: "United States", name: "Iowa" },
    KANSAS: { code: "KS", Country: "United States", name: "Kansas" },
    KENTUCKY: { code: "KY", Country: "United States", name: "Kentucky" },
    LOUISIANA: { code: "LA", Country: "United States", name: "Louisiana" },
    MAINE: { code: "ME", Country: "United States", name: "Maine" },
    MARYLAND: { code: "MD", Country: "United States", name: "Maryland" },
    MASSACHUSETTS: { code: "MA", Country: "United States", name: "Massachusetts" },
    MICHIGAN: { code: "MI", Country: "United States", name: "Michigan" },
    MINNESOTA: { code: "MN", Country: "United States", name: "Minnesota" },
    MISSISSIPPI: { code: "MS", Country: "United States", name: "Mississippi" },
    MISSOURI: { code: "MO", Country: "United States", name: "Missouri" },
    MONTANA: { code: "MT", Country: "United States", name: "Montana" },
    NEBRASKA: { code: "NE", Country: "United States", name: "Nebraska" },
    NEVADA: { code: "NV", Country: "United States", name: "Nevada" },
    NEWHAMPSHIRE: { code: "NH", Country: "United States", name: "New Hampshire" },
    NEWJERSEY: { code: "NJ", Country: "United States", name: "New Jersey" },
    NEWMEXICO: { code: "NM", Country: "United States", name: "New Mexico" },
    NEWYORK: { code: "NY", Country: "United States", name: "New York" },
    NORTHCAROLINA: { code: "NC", Country: "United States", name: "North Carolina" },
    NORTHDAKOTA: { code: "ND", Country: "United States", name: "North Dakota" },
    OHIO: { code: "OH", Country: "United States", name: "Ohio" },
    OKLAHOMA: { code: "OK", Country: "United States", name: "Oklahoma" },
    OREGON: { code: "OR", Country: "United States", name: "Oregon" },
    PENNSYLVANIA: { code: "PA", Country: "United States", name: "Pennsylvania" },
    RHODEISLAND: { code: "RI", Country: "United States", name: "Rhode Island" },
    SOUTHCAROLINA: { code: "SC", Country: "United States", name: "South Carolina" },
    SOUTHDAKOTA: { code: "SD", Country: "United States", name: "South Dakota" },
    TENNESSEE: { code: "TN", Country: "United States", name: "Tennessee" },
    TEXAS: { code: "TX", Country: "United States", name: "Texas" },
    UTAH: { code: "UT", Country: "United States", name: "Utah" },
    VERMONT: { code: "VT", Country: "United States", name: "Vermont" },
    VIRGINIA: { code: "VA", Country: "United States", name: "Virginia" },
    WASHINGTON: { code: "WA", Country: "United States", name: "Washington" },
    WESTVIRGINIA: { code: "WV", Country: "United States", name: "West Virginia" },
    WISCONSIN: { code: "WI", Country: "United States", name: "Wisconsin" },
    WYOMING: { code: "WY", Country: "United States", name: "Wyoming" }
};

var countryArray = new Array("Afghanistan", "Albania", "Algeria", "American Samoa", "Angola", "Anguilla", "Antartica", "Antigua and Barbuda",
    "Argentina", "Armenia", "Aruba", "Ashmore and Cartier Island", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
    "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
    "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde",
    "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Clipperton Island", "Cocos (Keeling) Islands",
    "Colombia", "Comoros", "Congo, Democratic Republic", "Congo, Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
    "Cyprus", "Czeck Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea",
    "Eritrea", "Estonia", "Ethiopia", "Europa Island", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana",
    "French Polynesia", "Antarctic Lands", "Gabon", "Gambia, The", "Gaza Strip", "Georgia", "Germany", "Ghana", "Gibraltar", "Glorioso Islands",
    "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island",
    "Holy See (Vatican City)", "Honduras", "Hong Kong", "Howland Island", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
    "Ireland, Northern", "Israel", "Italy", "Jamaica", "Jan Mayen", "Japan", "Jarvis Island", "Jersey", "Johnston Atoll", "Jordan", "Juan de Nova Island",
    "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
    "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Man, Isle of",
    "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia", "Midway Islands", "Moldova", "Monaco", "Mongolia",
    "Montserrat", "Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua",
    "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay",
    "Peru", "Philippines", "Pitcaim Islands", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romainia", "Russia", "Rwanda", "Saint Helena",
    "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon", "Saint Vincent", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia",
    "Scotland", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia",
    "Spain", "Spratly Islands", "Sri Lanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania",
    "Thailand", "Tobago", "Toga", "Tokelau", "Tonga", "Trinidad", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
    "United Kingdom", "Uruguay", "USA", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands", "Wales", "Wallis and Futuna", "West Bank", "Western Sahara",
    "Yemen", "Yugoslavia", "Zambia", "Zimbabwe");