<?xml version="1.0" encoding="utf-8"?><Database Name="MonkeyCRM" Class="MonkeyCRMOrganizationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=desktop-n8fhtdg;Initial Catalog=MonkeyCRM;Integrated Security=True" SettingsObjectName="WebCustomerRelationManagement.Models.Properties.Settings" SettingsPropertyName="MonkeyCRMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_WebsiteURL" Member="tbl_WebsiteURLs">
    <Type Name="tbl_WebsiteURL">
      <Column Name="slno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="websiteurl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="websiteurlid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="websiteurltype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="websiteurltypename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customertype" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="customertypename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isprimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statecodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statuscodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="createdbyname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="createdonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="createdonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ownername" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="departmentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="departmentname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Account_tbl_WebsiteURL" Member="tbl_Account" ThisKey="customertype" OtherKey="accountid" Type="tbl_Account" IsForeignKey="true" />
      <Association Name="tbl_Contact_tbl_WebsiteURL" Member="tbl_Contact" ThisKey="customertype" OtherKey="contactid" Type="tbl_Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Account" Member="tbl_Accounts">
    <Type Name="tbl_Account">
      <Column Name="slno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="accountnumber" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="accountid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="donotbulkemail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotemail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotbulkpostalmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotfax" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotphone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotpostalmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statecodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statuscodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="createdbyname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="createdonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="createdonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ownername" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="departmentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="departmentname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="primarycontactid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="primarycontactname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="tbl_Account_tbl_WebsiteURL" Member="tbl_WebsiteURLs" ThisKey="accountid" OtherKey="customertype" Type="tbl_WebsiteURL" />
      <Association Name="tbl_Account_tbl_Address" Member="tbl_Addresses" ThisKey="accountid" OtherKey="customertype" Type="tbl_Address" />
      <Association Name="tbl_Account_tbl_EmailAddress" Member="tbl_EmailAddresses" ThisKey="accountid" OtherKey="customertype" Type="tbl_EmailAddress" />
      <Association Name="tbl_Account_tbl_PhoneNumber" Member="tbl_PhoneNumbers" ThisKey="accountid" OtherKey="customertype" Type="tbl_PhoneNumber" />
      <Association Name="tbl_Contact_tbl_Account" Member="tbl_Contact" ThisKey="primarycontactid" OtherKey="contactid" Type="tbl_Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Address" Member="tbl_Addresses">
    <Type Name="tbl_Address">
      <Column Name="slno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="county" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="addressline1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="addressline2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="addressline3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="latitude" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="longitude" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="postalcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="postofficebox" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="stateorprovince" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="addressid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customertype" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="customertypename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isprimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statecodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statuscodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="createdbyname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="createdonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="createdonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ownername" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="departmentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="departmentname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Account_tbl_Address" Member="tbl_Account" ThisKey="customertype" OtherKey="accountid" Type="tbl_Account" IsForeignKey="true" />
      <Association Name="tbl_Contact_tbl_Address" Member="tbl_Contact" ThisKey="customertype" OtherKey="contactid" Type="tbl_Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Contact" Member="tbl_Contacts">
    <Type Name="tbl_Contact">
      <Column Name="slno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="middlename" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="contactid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contacttype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contacttypename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="donotbulkemail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotemail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotbulkpostalmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotfax" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotphone" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="donotpostalmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statecodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statuscodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="createdbyname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="createdonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="createdonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ownername" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="departmentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="departmentname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Contact_tbl_WebsiteURL" Member="tbl_WebsiteURLs" ThisKey="contactid" OtherKey="customertype" Type="tbl_WebsiteURL" />
      <Association Name="tbl_Contact_tbl_Account" Member="tbl_Accounts" ThisKey="contactid" OtherKey="primarycontactid" Type="tbl_Account" />
      <Association Name="tbl_Contact_tbl_Address" Member="tbl_Addresses" ThisKey="contactid" OtherKey="customertype" Type="tbl_Address" />
      <Association Name="tbl_Contact_tbl_EmailAddress" Member="tbl_EmailAddresses" ThisKey="contactid" OtherKey="customertype" Type="tbl_EmailAddress" />
      <Association Name="tbl_Contact_tbl_PhoneNumber" Member="tbl_PhoneNumbers" ThisKey="contactid" OtherKey="customertype" Type="tbl_PhoneNumber" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_EmailAddress" Member="tbl_EmailAddresses">
    <Type Name="tbl_EmailAddress">
      <Column Name="slno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="emailaddressname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="emailaddressid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customertype" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="customertypename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isprimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statecodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statuscodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="createdbyname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="createdonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="createdonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ownername" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="departmentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="departmentname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Account_tbl_EmailAddress" Member="tbl_Account" ThisKey="customertype" OtherKey="accountid" Type="tbl_Account" IsForeignKey="true" />
      <Association Name="tbl_Contact_tbl_EmailAddress" Member="tbl_Contact" ThisKey="customertype" OtherKey="contactid" Type="tbl_Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PhoneNumber" Member="tbl_PhoneNumbers">
    <Type Name="tbl_PhoneNumber">
      <Column Name="slno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phonenumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phonenumbertype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phonenumbertypename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phonenumberid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customertype" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="customertypename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="isprimary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="statecode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statecodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="statuscode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statuscodename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="createdbyname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="createdon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="createdonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="createdonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modifiedonbehalfby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedonbehalfbyname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ownerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ownername" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="departmentid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="departmentname" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Account_tbl_PhoneNumber" Member="tbl_Account" ThisKey="customertype" OtherKey="accountid" Type="tbl_Account" IsForeignKey="true" />
      <Association Name="tbl_Contact_tbl_PhoneNumber" Member="tbl_Contact" ThisKey="customertype" OtherKey="contactid" Type="tbl_Contact" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SystemUser" Member="tbl_SystemUsers">
    <Type Name="tbl_SystemUser">
      <Column Name="slno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="emailaddress" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="passwordkey" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="addressline1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="addressline2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="addressline3" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cretedon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="createdby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedby" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>