//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCustomerRelationManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonkeyCRMEntities : DbContext
    {
        public MonkeyCRMEntities()
            : base("name=MonkeyCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Account> tbl_Account { get; set; }
        public virtual DbSet<tbl_Address> tbl_Address { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
        public virtual DbSet<tbl_EmailAddress> tbl_EmailAddress { get; set; }
        public virtual DbSet<tbl_PhoneNumber> tbl_PhoneNumber { get; set; }
        public virtual DbSet<tbl_SystemUser> tbl_SystemUser { get; set; }
        public virtual DbSet<tbl_WebsiteURL> tbl_WebsiteURL { get; set; }
    }
}
