//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Organization
    {
        public int slno { get; set; }
        public System.Guid organizationid { get; set; }
        public string organizationname { get; set; }
        public string organizationurl { get; set; }
        public System.DateTime createdon { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string modifiedby { get; set; }
        public string createdbyname { get; set; }
        public string modifiedbyname { get; set; }
        public string statuscodename { get; set; }
        public Nullable<bool> statuscode { get; set; }
    }
}
