#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MonkeyCRMConfig")]
	public partial class OrganizationConfigDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Organization(tbl_Organization instance);
    partial void Updatetbl_Organization(tbl_Organization instance);
    partial void Deletetbl_Organization(tbl_Organization instance);
    #endregion
		
		public OrganizationConfigDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MonkeyCRMConfigConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OrganizationConfigDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrganizationConfigDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrganizationConfigDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OrganizationConfigDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Organization> tbl_Organizations
		{
			get
			{
				return this.GetTable<tbl_Organization>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Organization")]
	public partial class tbl_Organization : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _slno;
		
		private System.Guid _organizationid;
		
		private string _organizationname;
		
		private string _organizationurl;
		
		private System.DateTime _createdon;
		
		private System.Nullable<System.Guid> _createdby;
		
		private System.Nullable<System.DateTime> _modifiedon;
		
		private System.Nullable<System.Guid> _modifiedby;
		
		private string _createdbyname;
		
		private string _modifiedbyname;
		
		private string _statuscodename;
		
		private System.Nullable<bool> _statuscode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnslnoChanging(int value);
    partial void OnslnoChanged();
    partial void OnorganizationidChanging(System.Guid value);
    partial void OnorganizationidChanged();
    partial void OnorganizationnameChanging(string value);
    partial void OnorganizationnameChanged();
    partial void OnorganizationurlChanging(string value);
    partial void OnorganizationurlChanged();
    partial void OncreatedonChanging(System.DateTime value);
    partial void OncreatedonChanged();
    partial void OncreatedbyChanging(System.Nullable<System.Guid> value);
    partial void OncreatedbyChanged();
    partial void OnmodifiedonChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifiedonChanged();
    partial void OnmodifiedbyChanging(System.Nullable<System.Guid> value);
    partial void OnmodifiedbyChanged();
    partial void OncreatedbynameChanging(string value);
    partial void OncreatedbynameChanged();
    partial void OnmodifiedbynameChanging(string value);
    partial void OnmodifiedbynameChanged();
    partial void OnstatuscodenameChanging(string value);
    partial void OnstatuscodenameChanged();
    partial void OnstatuscodeChanging(System.Nullable<bool> value);
    partial void OnstatuscodeChanged();
    #endregion
		
		public tbl_Organization()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slno", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int slno
		{
			get
			{
				return this._slno;
			}
			set
			{
				if ((this._slno != value))
				{
					this.OnslnoChanging(value);
					this.SendPropertyChanging();
					this._slno = value;
					this.SendPropertyChanged("slno");
					this.OnslnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid organizationid
		{
			get
			{
				return this._organizationid;
			}
			set
			{
				if ((this._organizationid != value))
				{
					this.OnorganizationidChanging(value);
					this.SendPropertyChanging();
					this._organizationid = value;
					this.SendPropertyChanged("organizationid");
					this.OnorganizationidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationname", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string organizationname
		{
			get
			{
				return this._organizationname;
			}
			set
			{
				if ((this._organizationname != value))
				{
					this.OnorganizationnameChanging(value);
					this.SendPropertyChanging();
					this._organizationname = value;
					this.SendPropertyChanged("organizationname");
					this.OnorganizationnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationurl", DbType="VarChar(MAX)")]
		public string organizationurl
		{
			get
			{
				return this._organizationurl;
			}
			set
			{
				if ((this._organizationurl != value))
				{
					this.OnorganizationurlChanging(value);
					this.SendPropertyChanging();
					this._organizationurl = value;
					this.SendPropertyChanged("organizationurl");
					this.OnorganizationurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdon", DbType="DateTime NOT NULL")]
		public System.DateTime createdon
		{
			get
			{
				return this._createdon;
			}
			set
			{
				if ((this._createdon != value))
				{
					this.OncreatedonChanging(value);
					this.SendPropertyChanging();
					this._createdon = value;
					this.SendPropertyChanged("createdon");
					this.OncreatedonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this.OncreatedbyChanging(value);
					this.SendPropertyChanging();
					this._createdby = value;
					this.SendPropertyChanged("createdby");
					this.OncreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedon", DbType="DateTime")]
		public System.Nullable<System.DateTime> modifiedon
		{
			get
			{
				return this._modifiedon;
			}
			set
			{
				if ((this._modifiedon != value))
				{
					this.OnmodifiedonChanging(value);
					this.SendPropertyChanging();
					this._modifiedon = value;
					this.SendPropertyChanged("modifiedon");
					this.OnmodifiedonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedby", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> modifiedby
		{
			get
			{
				return this._modifiedby;
			}
			set
			{
				if ((this._modifiedby != value))
				{
					this.OnmodifiedbyChanging(value);
					this.SendPropertyChanging();
					this._modifiedby = value;
					this.SendPropertyChanged("modifiedby");
					this.OnmodifiedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdbyname", DbType="VarChar(MAX)")]
		public string createdbyname
		{
			get
			{
				return this._createdbyname;
			}
			set
			{
				if ((this._createdbyname != value))
				{
					this.OncreatedbynameChanging(value);
					this.SendPropertyChanging();
					this._createdbyname = value;
					this.SendPropertyChanged("createdbyname");
					this.OncreatedbynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedbyname", DbType="VarChar(MAX)")]
		public string modifiedbyname
		{
			get
			{
				return this._modifiedbyname;
			}
			set
			{
				if ((this._modifiedbyname != value))
				{
					this.OnmodifiedbynameChanging(value);
					this.SendPropertyChanging();
					this._modifiedbyname = value;
					this.SendPropertyChanged("modifiedbyname");
					this.OnmodifiedbynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statuscodename", DbType="VarChar(MAX)")]
		public string statuscodename
		{
			get
			{
				return this._statuscodename;
			}
			set
			{
				if ((this._statuscodename != value))
				{
					this.OnstatuscodenameChanging(value);
					this.SendPropertyChanging();
					this._statuscodename = value;
					this.SendPropertyChanged("statuscodename");
					this.OnstatuscodenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statuscode", DbType="Bit")]
		public System.Nullable<bool> statuscode
		{
			get
			{
				return this._statuscode;
			}
			set
			{
				if ((this._statuscode != value))
				{
					this.OnstatuscodeChanging(value);
					this.SendPropertyChanging();
					this._statuscode = value;
					this.SendPropertyChanged("statuscode");
					this.OnstatuscodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
